// src/app/layout.tsx
import type { Metadata } from "next";
import './globals.css';

export const metadata: Metadata = {
  title: "Studymate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen w-screen bg-gradient-to-b from-white to-blue-200">
          {/* Header */}
          <div className="bg-gradient-to-r from-blue-800 via-purple-500 to-pink-400 w-full h-20 shadow-2xl flex items-center pl-4">
            <h1 className="text-4xl text-white font-bold">Studymate</h1>
          </div>

          {/* Page Content (fills remaining space) */}
          <div className="flex-1 flex items-center justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
