import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: "Studymate",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body>
        <div>
          <div className='flex bg-gradient-to-r from-blue-800 via-purple-500 to-pink-400 static w-screen h-18 shadow-black-400/50 shadow-2xl'>
            <div className='content-end'>
              <h1 className='pb-2 pl-2 font-sans text-5xl text-white'>Studymate</h1>
            </div>
          </div>
          <div className='h-screen w-screen bg-gradient-to-b from-white to-blue-200'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
