name: Deploy LMS to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Trigger Backend Deploy on Render
      run: |
        curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

    - name: Trigger Frontend Deploy on Render
      run: |
        curl -X POST ${{ secrets.VERCEL_FRONTEND_HOOK }}
