name: CI/CD for LMS

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        run: |
          cd backend
          npm test -- --forceExit --detectOpenHandles

      - name: Deploy Backend to Render
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

      - name: Deploy Frontend to Render
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}
